import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { Inter } from "next/font/google";
import { AuthProvider } from "@/contexts/auth-context";
import Footer from "@/components/ui/footer";
import Navbar from "@/components/nav/navbar";
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={` ${inter.variable} ${geistSans.variable} ${geistMono.variable} `}
    >
      <body className={`bg-gradient relative font-sans antialiased`}>
        <div className="pointer-events-none absolute top-0 left-0 -z-10 h-screen w-full overflow-hidden">
          <img
            src="/assets/line-back.svg"
            alt="background lines"
            className="h-screen w-full object-cover"
            draggable="false"
            aria-hidden="true"
          />
        </div>
        <AuthProvider>
          <Navbar />
          {children}
        </AuthProvider>
        <Footer />
      </body>
    </html>
  );
}
